[WIP]RecyclerViewの設計
ShebangDog/20dojo_and pull request #16
Opened 2020-09-02 01:25 UTC by ns679

・行ったこと
メモ一覧画面の設計とそのバッググラウンドのプログラムを書いた
・行った理由
今回のメモ一覧でRecyclerviewを使用するため
・どのようにして行ったか
https://qiita.com/Todate/items/297bc3e4d0f3d2477ed3
このサイトを参考に作成した。

補足
実行してみると分かるがうまくプログラムが作動しない。

2020-09-02 01:40 UTC, ShebangDog commented on app/src/main/java/jp/co/cyberagent/dojo2020/ui/main/RecyclerAdapter.kt
> +    private var mRecyclerView: RecyclerView? = null
`private var mRecyclerView: RecyclerView? = null`
 
adapterがrecyclerViewを持つことはない気がする。
基本的にはadapterへデータのリストを渡すだけでいい!!!

2020-09-02 01:43 UTC, ShebangDog requested changes
ここ(https://akira-watson.com/android/recyclerview.html)とかここ(https://developer.android.com/guide/topics/ui/layout/recyclerview?hl=ja)をみてもう一度やってみてください!!!

2020-09-02 05:14 UTC, ns679 commented
![image](https://user-images.githubusercontent.com/40596869/91934524-8d193100-ed26-11ea-9a7a-550854fe89da.png)

2020-09-02 05:57 UTC, ns679 commented
![image](https://user-images.githubusercontent.com/40596869/91937333-a0c79600-ed2c-11ea-8b13-914195a73e4a.png)

2020-09-02 06:03 UTC, ns679 commented
![image](https://user-images.githubusercontent.com/40596869/91937674-61e61000-ed2d-11ea-9f3e-eedbb2f69c02.png)

2020-09-02 06:06 UTC, ns679 commented
![image](https://user-images.githubusercontent.com/40596869/91937884-dc169480-ed2d-11ea-8067-f6e6fa1d8bb7.png)
![image](https://user-images.githubusercontent.com/40596869/91937896-e3d63900-ed2d-11ea-91da-3fdf620c40f6.png)

2020-09-02 09:58 UTC, ShebangDog requested changes
レビューコメント参照してください!

2020-09-02 09:58 UTC, ShebangDog commented on app/src/main/java/jp/co/cyberagent/dojo2020/ui/main/RecyclerAdapter.kt
> +class RecyclerAdapter(private val a: MutableList<String>):RecyclerView.Adapter<RecyclerViewHolder>() {
MutableList<String>のaの変数名を変更してほしいのと、そいつの型をList<String>に変えておいてほしい!!!

2020-09-02 09:58 UTC, ShebangDog commented on app/src/main/java/jp/co/cyberagent/dojo2020/ui/main/RecyclerViewHolder.kt
> +
スペースが気になるのでいい感じに直しておいてほしい!!!

2020-09-02 09:58 UTC, ShebangDog commented on app/src/main/res/layout/recyclerview_page.xml
> +        android:id="@+id/recyclerView2"
idをsnake_caseを使って変更してほしい
今回だとrecyclerView2 から recycler_view_2に変更してほしい
あと、2は特に意味も持ってなさそうなので消しておいてほしい!
最終的には recycler_view にすることを想定してる!

2020-09-02 09:58 UTC, ShebangDog commented on app/src/main/res/layout/recyclerview_page.xml
> +        android:id="@+id/bottomNavigationView2"
ここも上のと同じことしてほしい

2020-09-03 02:26 UTC, ShebangDog requested changes
命名規則の部分で変更をお願いしたい!

2020-09-03 02:26 UTC, ShebangDog commented on app/src/main/java/jp/co/cyberagent/dojo2020/ui/main/RecyclerAdapter.kt
> +        val View = LayoutInflater.from(parent.context).inflate(R.layout.list_item,parent,false)
View -> view

2020-09-03 02:26 UTC, ShebangDog commented on app/src/main/res/layout/recyclerview_page.xml
> +        android:id="@+id/recycler_View"
recycler_View -> recycler_view

2020-09-03 02:26 UTC, ShebangDog commented on app/src/main/res/layout/recyclerview_page.xml
> +        @+id/bottomNavigationView2"
bottomNavigationView2 -> bottom_navigation_view

2020-09-03 02:26 UTC, ShebangDog commented on app/src/main/res/layout/recyclerview_page.xml
> +        android:id="@+id/bottom_Navigation_View"
bottom_navigation_view

2020-09-03 02:58 UTC, asagi71 commented
いいと思います

2020-09-03 02:58 UTC, merged